#!/usr/bin/env bash
out="$HOME/.config/quickshell/tree/apps.js"
tmp=$(mktemp)

esc() { local s="$1"; s=${s//\\/\\\\}; s=${s//\"/\\\"}; printf '%s' "$s"; }

find_icon() {
  local name="$1"
  [ -z "$name" ] && return 1
  # reject absolute paths that aren't images
  if [[ "$name" = /* ]]; then
    [[ "$name" =~ \.(png|svg|xpm|ico)$ ]] && [ -f "$name" ] && { printf '%s' "$name"; return 0; }
    return 1
  fi
  local b s ext
  for b in "$HOME/.local/share/icons/hicolor" \
           "/usr/share/icons/hicolor" \
           "/var/lib/flatpak/exports/share/icons/hicolor" \
           "$HOME/.local/share/flatpak/exports/share/icons/hicolor"; do
    for s in 128x128 96x96 64x64 48x48 256x256 scalable; do
      for ext in png svg xpm; do
        [ -f "$b/$s/apps/$name.$ext" ] && { printf '%s' "$b/$s/apps/$name.$ext"; return 0; }
      done
    done
  done
  for ext in png svg xpm; do
    [ -f "/usr/share/pixmaps/$name.$ext" ] && { printf '%s' "/usr/share/pixmaps/$name.$ext"; return 0; }
  done
  return 1
}

{
  for d in "$HOME/.local/share/applications" \
           "$HOME/.local/share/flatpak/exports/share/applications" \
           "/var/lib/flatpak/exports/share/applications" \
           "/usr/share/applications" \
           "/usr/local/share/applications"; do
    [ -d "$d" ] || continue
    for f in "$d"/*.desktop; do [ -f "$f" ] && printf '%s\n' "$f"; done
  done
} | while read -r f; do
  meta=$(awk '
    /^Name=/          { if (name=="") name=substr($0,6) }
    /^Categories=/    { cats=substr($0,12) }
    /^Keywords=/      { kw=substr($0,10) }
    /^Icon=/          { if (ico=="") ico=substr($0,6) }
    /^Exec=/          { if (exe=="") exe=substr($0,6) }
    /^Terminal=true/  { termfl=1 }
    /^Hidden=true/    { hidden=1 }
    /^NoDisplay=true/ { nodisplay=1 }
    END {
      if (name=="" || hidden || nodisplay) exit
      n=split(cats, arr, ";"); cat=""
      for (i=n; i>=1; i--) if (arr[i]!="") { cat=arr[i]; break }
      if (cat=="") cat="Other"
      gsub(/;/, " ", kw)
      gsub(/%[a-zA-Z]/, "", exe)
      printf "%s\t%s\t%s\t%s\t%s\t%s", name, cat, kw, ico, exe, (termfl ? "1" : "0")
    }' "$f")
  [ -z "$meta" ] && continue
  IFS=$'\t' read -r name cat kw ico exe termfl <<< "$meta"
  [ -z "$exe" ] && continue
  iconfile=$(find_icon "$ico") || iconfile=""
  printf '  {label:"%s",cat:"%s",keywords:"%s",path:"%s",icon:"%s",exec:"%s",terminal:%s},\n' \
    "$(esc "$name")" "$(esc "$cat")" "$(esc "$kw")" "$(esc "$f")" "$(esc "$iconfile")" "$(esc "$exe")" \
    "$([ "$termfl" = "1" ] && echo true || echo false)" >> "$tmp"
done

{
  echo "// generated by list-apps.sh — do not edit"
  echo "var list = ["
  cat "$tmp"
  echo "];"
} > "$out"
rm -f "$tmp"
